
guangzhou:
  aqi_rul: "http://139.159.198.98/pubDataServer/getPmRank?apikey=0710d94cebb4248a38edef859d11ab35"
  aqi_sql: "select * from xy_w2_pm25 where  isvalid='1'"
  location_url: "http://139.159.198.98/vivoDbServer/locationgeo?apikey=0710d94cebb4248a38edef859d11ab35&longitude=%f&latitude=%f&locationSystem=GCJ02&language=zh-cn"
  location_sql: "SELECT * FROM xy_w2_city_crawl_china_list a WHERE citycode COLLATE utf8mb4_general_ci IN (SELECT area_code FROM `mingzhenbu_city`) AND citycode != parentcode"
  atmosphere_track: "http://typhoon.nmc.cn/weatherservice/typhoon/jsons/view_%s"
  atmosphere_list: "http://typhoon.nmc.cn/weatherservice/typhoon/jsons/list_default?t=1610502450124&callback=typhoon_jsons_list_default"
  typhoon_list_sql: "select * from typhoon_list"
  typhoon_track_sql: "select * from typhoon_track where typhoon_name_en = '%s' and t2 ='00' ORDER BY t1"
  typhoon_track_url: "http://139.159.198.98/pubDataServer/gettyphoon?apikey=0710d94cebb4248a38edef859d11ab35&typhoonid=%s"
  typhoon_list_url: "http://139.159.198.98/pubDataServer/gettyphoonlist?apikey=0710d94cebb4248a38edef859d11ab35"

shanghai:
  aqi_rul: "http://pub.zuimeitianqi.com/pubDataServer/getPmRank?apikey=0710d94cebb4248a38edef859d11ab35"
  aqi_sql: "select * from xy_w2_pm25 where  isvalid='1'"
  location_url: "http://pub.zuimeitianqi.com/vivoDbServer/locationgeo?apikey=0710d94cebb4248a38edef859d11ab35&longitude=%f&latitude=%f&locationSystem=GCJ02&language=zh-cn"
  location_sql: "SELECT * FROM xy_w2_city_crawl_china_list a WHERE citycode COLLATE utf8mb4_general_ci IN (SELECT area_code FROM `mingzhenbu_city`) AND citycode != parentcode"
  atmosphere_track: "http://typhoon.nmc.cn/weatherservice/typhoon/jsons/view_%s"
  atmosphere_list: "http://typhoon.nmc.cn/weatherservice/typhoon/jsons/list_default?t=1610502450124&callback=typhoon_jsons_list_default"
  typhoon_list_sql: "select * from typhoon_list"
  typhoon_track_sql: "select * from typhoon_track where typhoon_name_en = '%s' and t2 ='00' ORDER BY t1"
  typhoon_track_url: "http://pub.zuimeitianqi.com/pubDataServer/gettyphoon?apikey=0710d94cebb4248a38edef859d11ab35&typhoonid=%s"
  typhoon_list_url: "http://pub.zuimeitianqi.com/pubDataServer/gettyphoonlist?apikey=0710d94cebb4248a38edef859d11ab35"

shanghai_minutes:
  aqi_url: "http://pub.zuimeitianqi.com/pubDataServer/getPmRank?apikey=0710d94cebb4248a38edef859d11ab35"
  aqi_sql: "select * from xy_w2_pm25 where city_id = (select cityCode from xy_w2_city_crawl_china_list WHERE accuCode='%s') and isvalid='1'"
  location_url: "http://pub.zuimeitianqi.com/vivoDbServer/locationgeo?apikey=0710d94cebb4248a38edef859d11ab35&longitude=%f&latitude=%f&locationSystem=GCJ02&language=zh-cn"
  typhoon_list_url: "http://pub.zuimeitianqi.com/pubDataServer/gettyphoonlist?apikey=0710d94cebb4248a38edef859d11ab35"
  typhoon_track_sql: "select * from typhoon_track WHERE typhoon_code= '%s' and t2 ='00' GROUP BY t1 ORDER BY t1"
  location_sql: "SELECT * FROM xy_w2_city_crawl_china_list a WHERE accuCode='1921951' "
  typhoon_track_url: "http://pub.zuimeitianqi.com/pubDataServer/gettyphoon?apikey=0710d94cebb4248a38edef859d11ab35&typhoonid=%s"

guangzhou_minutes:
  aqi_url: "http://139.159.198.98/pubDataServer/getPmRank?apikey=0710d94cebb4248a38edef859d11ab35"
  aqi_sql: "select * from xy_w2_pm25 where city_id = (select cityCode from xy_w2_city_crawl_china_list WHERE accuCode='%s') and isvalid='1'"
  location_url: "http://139.159.198.98/vivoDbServer/locationgeo?apikey=0710d94cebb4248a38edef859d11ab35&longitude=%f&latitude=%f&locationSystem=GCJ02&language=zh-cn"
  typhoon_list_url: "http://139.159.198.98/pubDataServer/gettyphoonlist?apikey=0710d94cebb4248a38edef859d11ab35"
  typhoon_track_sql: "select * from typhoon_track WHERE typhoon_code= '%s' and t2 ='00' GROUP BY t1 ORDER BY t1"
  location_sql: "SELECT * FROM xy_w2_city_crawl_china_list a WHERE accuCode='1921951' "
  typhoon_track_url: "http://139.159.198.98/pubDataServer/gettyphoon?apikey=0710d94cebb4248a38edef859d11ab35&typhoonid=%s"


large_particles:
  sql: "SELECT * FROM `xy_w2_city_crawl_oversea_list`  limit %d, %d"
  baseurl: "http://139.159.198.98/pubDataServer/getweatherpub?apikey=0710d94cebb4248a38edef859d11ab35&citycode=&language=zh_CN&lon=%f&lat=%f&chl=&codeType=1"
  guangzhou_150million_url: "http://139.159.198.98/pubDataServer/getweatherpub?apikey=0710d94cebb4248a38edef859d11ab35&citycode=%s&language=zh_CN&lon=&lat=&chl=&codeType=1"
  shanghai_150million_url: "http://pub.zuimeitianqi.com/pubDataServer/getweatherpub?apikey=0710d94cebb4248a38edef859d11ab35&citycode=%s&language=zh_CN&lon=&lat=&chl=&codeType=1"
  150million_sql: "SELECT * FROM `xy_w2_city_relation_search_huawei` WHERE language_code = 'zh-cn' AND country_id != 'CN' LIMIT %s,%s"

mysql:
  host: 139.9.217.1
  user: testDbUser
  password: Bestweather_zmtq^#@2020
  db: weather
  port: 4108
  charset: utf8

